name: FancyRoulette
main: cokoc.fancyroulette.FancyRoulette
version: 1.0.6
author: CoKoC
description: Lets user play on admin-created roulette tables.
depend: [Vault]

commands:
  roulette:
    description: Manages creation of roulettes.
    usage: /roulette [id] {spinner}